### ISSUE TITLE
What is the instructBLIP prompt used in the paper?

### ISSUE THREAD

**Issue by 18445864529** [AoiDragon/POPE#10]
Hi. I would like to know how you managed to let instructBLIP answer the yes or no question. In my experiment, it never follows the instructions. It generates only "1 \<s\>" "3 \<s\>"  "0 \<s\>" etc

**Comment by AoiDragon** [comment]
Hello, @18445864529 

We followed the default settings of InstructBLIP and didn't use any other prompt formats. Could you possibly check the vicuna version you're using? InstructBLIP requires vicuna version 1.1.

**Comment by 18445864529** [comment]
It's indeed very weird that when I use the template "Question: {} Answer: "
it gives only digits (0, 1, 2...)
But by simply replacing 'Answer: ' with 'Short answer:' it gives the
correct response. (Note that also excluded the space after the colon)

**Comment by AoiDragon** [comment]
We didn't use the template "Question: {} Answer: " when evaluating InstructBLIP on POPE. We directly prompt the model with POPE questions.
