### ISSUE TITLE
Word 'imange' in POPE questions

### ISSUE THREAD

**Issue by SammyCui** [AoiDragon/POPE#11]
Hello,

Thank you for the nice work!

Just a quick question... I noticed there are 'imange' instead of 'image' in the annotation json files. Is it a typo or it is really 'imange' intentionally (since there are many of them). Sorry if I missed anything from the paper. 

Thanks for the help!

**Comment by AoiDragon** [comment]
Hello, @SammyCui 

These are indeed typos and I have fixed them. Thanks for your reminder!
