### ISSUE TITLE
InstructBLIP generation parameters

### ISSUE THREAD

**Issue by JulioZhao97** [AoiDragon/POPE#12]
Hello, I want to ask what generation parameters and what language model or pretrained weight you guys use in producing results in the paper?  In our practice, we found that InstructBLIP results are much higher than results in the paper.

For example, in popular and adversarial, our accuracy results are 84% and 81%, however in paper results are 71% and 62%

**Comment by JulioZhao97** [comment]
sorry, my bad, the results I should refer to is this:
<img width="796" alt="image" src="https://github.com/AoiDragon/POPE/assets/40555727/94ea5c77-3912-45e8-9641-09e20a71bdb7">
but the gap is still large

**Comment by AoiDragon** [comment]
Hello, @JulioZhao97 

We used the default parameter settings of InstructBLIP and we didn't use any system prompt.

**Comment by JulioZhao97** [comment]
Did the results in Table4 (the above results) evaluated using json files in ```output/coco```?

**Comment by JulioZhao97** [comment]
Thanks for your time, it seems that whether or not the first letter of prompt is capitalized has a big impact on performance
