### ISSUE TITLE
Question about Figure 2.

### ISSUE THREAD

**Issue by p1k0pan** [AoiDragon/POPE#13]
First of all congrats your greate work!

My question is how to find out the Hallucination times of a model just like the Figure 2 shows. I assume the file `segmentation/coco_ground_truth_segmentation.json` is the ground truth to show what objects are actually shown in the corresponding image. Then base on the caption data you store on `caption_data/Instruction1_instructblip.json`, I assume you use  the `generate` of the model to describe some images so that you could compare the objects that model predicts and the objects in ground truth.

But how to evaluate the prediction and the ground truth objects? The predicted objects that not included in ground truth object list should be just put in hallucinations? And how to handle the synonym objects for example, predicted objects: **man** and ground truth object: **person**. It shouldn't be hallucination, right?

Looking forward to your response :)

**Comment by AoiDragon** [comment]
Hello, @p1k0pan

Figure 2 illustrates the concept of object hallucination, which is a little different from the real evaluation process. We adopt CHAIR to evaluate object hallucination, which only considers the 80 COCO objects. Other objects are not taken into consideration even if they are hallucinated. CHAIR also adopts a synonym list to avoid missing the synonym cases as you mentioned. You can refer to the original paper "Object Hallucination in Image Captioning" for more details.

**Comment by p1k0pan** [comment]
Thank you
