### ISSUE TITLE
Could you please comment on which LLAVA model did you use in the paper? e.g., Table 3

### ISSUE THREAD

**Issue by pritamqu** [AoiDragon/POPE#14]
Could you please comment on which LLAVA model did you use in the paper? Could you please share either name or link of the exact model as per https://github.com/haotian-liu/LLaVA/blob/main/docs/MODEL_ZOO.md. 
I am trying to reproduce the POPE results of llava but mine is quite different than what was reported in your paper.

**Comment by pritamqu** [comment]
also could you please share the parameter setup that you used for llava. i.e., temp, max_tokens?

**Comment by AoiDragon** [comment]
Hello @pritamqu. The LLaVA model we used is based on vicuna 13b v0, the huggingface link is https://huggingface.co/liuhaotian/LLaVA-13b-delta-v0. And we follow the default generation parameter of LLaVA.

**Comment by pritamqu** [comment]
thank you
