### ISSUE TITLE
One question about the evaluation on A-OKVQA

### ISSUE THREAD

**Issue by k1tano** [AoiDragon/POPE#2]
The AOKVAQ dataset does not provide labels for the test set, are you using the validation set for the evaluation?

**Comment by Richar-Du** [comment]
Thanks for your question. We evaluated on the validation set of A-OKVQA, sorry for the missing clarification. We will add this in our updated version.

**Comment by k1tano** [comment]
> Thanks for your question. We evaluated on the validation set of A-OKVQA, sorry for the missing clarification. We will add this in our updated version.

Thank you for your reply. I have another question to ask: AOKVQA dataset provides two kinds of answers. One is the only correct answer in multiple choice, and the other is the direct answer that may contain multiple answers. Which one do you use when provided to chatgpt？

**Comment by Richar-Du** [comment]
Like GQA and other VQA tasks, we use the direct answer instead of the multiple choice.
