### ISSUE TITLE
GQA 500 samples

### ISSUE THREAD

**Issue by xinyu1205** [AoiDragon/POPE#4]
Hi, thanks for your amazing work!
I would like to inquire if you can provide 500 samples randomly selected from GQA. This would be incredibly helpful for my evaluation, and I will definitely giving proper citation.

> ”there are 132,062 questions in the balanced validation set of GQA, we only randomly sample 500 among them for evaluation)“

I will be waiting for your answers :)
Best wishes!

**Comment by AoiDragon** [comment]
Hi, thanks for your attention to our work!

I have uploaded the COCO filenames of the 500 images we utilized. You can access them at [here](https://drive.google.com/file/d/10XDM-yl8t_-u_IftToRn2XGNbJtUYKAh/view?usp=sharing).

**Comment by xinyu1205** [comment]
Thanks for your very quick and kind reply!

**Comment by xinyu1205** [comment]
Hi, I think you misunderstood my question. I would like 500 samples from the GQA dataset instead of COCO. Can you share the 500 samples from GQA?

**Comment by AoiDragon** [comment]
Sorry for any confusion. I re-uploaded the GQA samples at [here](https://drive.google.com/file/d/1sYtj8HUod_gGWtpiAu2w3gdLXLP3dzcx/view?usp=sharing). Hope this time they can help you :)

**Comment by xinyu1205** [comment]
I sincerely appreciate your patience and help!
Based on the file name JSON file you provided, as well as the validation JSON file from GQA official, I've compiled a total of 10,688 questions.  I surmise that you might not have utilized all of these questions, so could you possibly provide the specific subset of questions?
In addition, I am a PhD student at Fudan University, and it would be very honored to contact you through WeChat. My WeChat is ID "huangxinyu1205".
Best wishes!
