### ISSUE TITLE
Reproduce Table 6: the json files of COCO, A-OKVQA and GQA

### ISSUE THREAD

**Issue by xieyuquanxx** [AoiDragon/POPE#5]
Hi, thanks for your valuable contributions!
I want to reproduce the result of table 6. However, I have encountered an issue when running the script to generate the POPE dataset. It appears that running the script results in different JSON files each time.
Would it be possible for you to share the final JSON files for the COCO, A-OKVQA, and GQA datasets after running the build script?
`python main.py --auto_seg True --img_path ./segmentation/<coco><A-OKVQA><GQA>_val_images.json --seg_num 1000`
Having access to these final JSON files would greatly assist me in my research. 
Looking forward to your early reply! :)
Best Wish!

**Comment by xieyuquanxx** [comment]
Hi, I meet another problem. 
When I decide to reproduce Table 5, POPE dataset is Random and use InstructBLIP-vicuna13b-v1.1, I got higher result than your report. 
My result is `89.21, 86.69, 93.4, 89.92, 55.53` which represent Accuracy, Precision, Recall, F1 Score and Yes ratio respectively.
Your result is`88.57, 84.09, 95.13, 89.27, 56.57`.
Also, I just use the json files from the github repo. `output/coco/coco_pope_<random><popular><adversiral>.json`.
To get generate text, I use blow method and parameter,
```python
output_text = model.generate(
    samples,
    length_penalty=float(1),
    repetition_penalty=float(1.5),
    num_beams=5,
    max_length=20,
    min_length=1,
    top_p=0.9,
    use_nucleus_sampling=False,
)
```
Can you provide me more detail information about how to evaluation InstructBLIP? Thank you! :)

**Comment by AoiDragon** [comment]
Hi, thanks for your attention to our work.
For your first questions, I upload the pope file we used in table 6 in this [link](https://drive.google.com/drive/folders/1vdHHi38KZ0iZZ28EpDHvTZFqLiNBcnla?usp=drive_link).
For the second one, we follow the default settings of InstructBLIP:
```
def generate(
            self,
            samples,
            use_nucleus_sampling=False,
            num_beams=5,
            max_length=256,
            min_length=1,
            top_p=0.9,
            repetition_penalty=1.5,
            length_penalty=1,
            num_captions=1,
            temperature=1,
    ):
```

**Comment by xieyuquanxx** [comment]
Thank you for your reply! 

> Hi, thanks for your attention to our work. For your first questions, I upload the pope file we used in table 6 in this [link](https://drive.google.com/drive/folders/1vdHHi38KZ0iZZ28EpDHvTZFqLiNBcnla?usp=drive_link). For the second one, we follow the default settings of InstructBLIP:
> 
> ```
> def generate(
>             self,
>             samples,
>             use_nucleus_sampling=False,
>             num_beams=5,
>             max_length=256,
>             min_length=1,
>             top_p=0.9,
>             repetition_penalty=1.5,
>             length_penalty=1,
>             num_captions=1,
>             temperature=1,
>     ):
> ```
