### ISSUE TITLE
Generated Questions for A-OKVQA and GQA

### ISSUE THREAD

**Issue by LengSicong** [AoiDragon/POPE#7]
Thanks for your great work! We are currently following your work on the object hallucinations and developing technique to mitigate this issue.
May I know if you can publish the generated questions for GQA and A-OKVQA with random, popular, and adversarial splits?

**Comment by AoiDragon** [comment]
Hello @LengSicong ,

Thank you for your interest in our work. I've uploaded the SEEM-based POPE for AOKVQA and GQA. You can find them at [here](https://github.com/AoiDragon/POPE/tree/main/output/seem).

I hope these resources will be beneficial to your research.

**Comment by LengSicong** [comment]
Thanks a lot for your publication!
