### ISSUE TITLE
quite a few labeling errors in pope coco annotations

### ISSUE THREAD

**Issue by Maxlinn** [AoiDragon/POPE#8]
hello aoidragon and the team, thank for your work of pope!

recently i am using pope coco (random/adverserial/popular) to measure hallucination of my LVLM, however, i found quite a few labeling errors in the released data. i am using the [newest commit](https://github.com/AoiDragon/POPE/commit/9b5410653a70098c433574841a1804b89f573575). i sincerely hope you could look into this matter.

here are some cases:

random: `{'question_id': 1271, 'image': 'COCO_val2014_000000244455.jpg', 'text': 'Is there a bicycle in the image?', 'label': 'yes'}`
> there seems no bicycle

![图片](https://github.com/AoiDragon/POPE/assets/43326876/97878788-fd3e-4458-ac0d-4baf7e7ca279)

random: {'question_id': 1761, 'image': 'COCO_val2014_000000346707.jpg', 'text': 'Is there a bowl in the image?', 'label': 'yes'}
> there is no bowl

![图片](https://github.com/AoiDragon/POPE/assets/43326876/e3618c11-6892-484f-9ef8-d84a2210c7b3)

random: {'question_id': 1593, 'image': 'COCO_val2014_000000485485.jpg', 'text': 'Is there a car in the image?', 'label': 'yes'}
> there seems no car

![图片](https://github.com/AoiDragon/POPE/assets/43326876/9a0423b1-c43a-49a6-a38a-4313aef5839a)

adverserial: {'question_id': 2375, 'image': 'COCO_val2014_000000325347.jpg', 'text': 'Is there a sports ball in the image?', 'label': 'yes'}
> there is no ball

![图片](https://github.com/AoiDragon/POPE/assets/43326876/026314ea-0d18-4415-af2a-7b957430424a)

adverserial: {'question_id': 1051, 'image': 'COCO_val2014_000000018150.jpg', 'text': 'Is there a backpack in the image?', 'label': 'yes'}
> there is no backpack

![图片](https://github.com/AoiDragon/POPE/assets/43326876/a46ffb8e-f8ce-4f98-bb8a-9fe35a68a7ac)

adverserial: {'question_id': 1327, 'image': 'COCO_val2014_000000287035.jpg', 'text': 'Is there a tv in the image?', 'label': 'yes'}
> there is no tv

![图片](https://github.com/AoiDragon/POPE/assets/43326876/cad6a055-0f9d-48c3-85d5-bb77e2377089)

**Comment by Maxlinn** [comment]
these are some samples, not all errors. i actually come across labeling errors quite often when i look at the cases that my lvlm failed(about 1000)

**Comment by AoiDragon** [comment]
Hello, @Maxlinn 

We build the POPE questions based on the object annotations of COCO.  I've reviewed the annotations of the images you've referenced and confirmed that these objects are indeed present. Here are some examples:

![WX20231029-160337@2x](https://github.com/AoiDragon/POPE/assets/59017650/ca06f256-3453-4fa4-b6d0-4187c6d7a41b)
![WX20231029-160406@2x](https://github.com/AoiDragon/POPE/assets/59017650/6c50ce74-1de4-4149-b562-bc49b885ca35)
![WX20231029-160858@2x](https://github.com/AoiDragon/POPE/assets/59017650/827663f2-ebc8-4774-b812-b1ab375479ae)

Anyway, thanks for your detailed check and we'll take your feedback into consideration as we look to enhance our dataset in the future.

**Comment by Maxlinn** [comment]
much thanks for timely responding! i sincerely apologize for my oversight for the details. some objects do exist but not easy to find. but i still doubt some other cases, including the tv case and the bowl case. the overall quality of pope is ensured, thanks for bringing about the dataset!

**Comment by zwbx** [comment]
Hello, I also find the same error in practice.
May I ask how do you get this name list for each image?
I call coco API to check it and find it is not consistent with the picture of name list you shown above.

> Hello, @Maxlinn
> 
> We build the POPE questions based on the object annotations of COCO. I've reviewed the annotations of the images you've referenced and confirmed that these objects are indeed present. Here are some examples:
> 
> ![WX20231029-160337@2x](https://user-images.githubusercontent.com/59017650/278858668-ca06f256-3453-4fa4-b6d0-4187c6d7a41b.png) ![WX20231029-160406@2x](https://user-images.githubusercontent.com/59017650/278858678-6c50ce74-1de4-4149-b562-bc49b885ca35.png) ![WX20231029-160858@2x](https://user-images.githubusercontent.com/59017650/278858736-827663f2-ebc8-4774-b812-b1ab375479ae.png)
> 
> Anyway, thanks for your detailed check and we'll take your feedback into consideration as we look to enhance our dataset in the future.
