### ISSUE TITLE
Hello, I also find the label error in practice.

### ISSUE THREAD

**Issue by zwbx** [AoiDragon/POPE#9]
Hello, I also find the same error in practice.
May I ask how do you get this name list for each image?
I call coco API to check it and find it is not consistent with the picture of name list you shown above.

> Hello, @Maxlinn
> 
> We build the POPE questions based on the object annotations of COCO. I've reviewed the annotations of the images you've referenced and confirmed that these objects are indeed present. Here are some examples:
> 
> ![WX20231029-160337@2x](https://user-images.githubusercontent.com/59017650/278858668-ca06f256-3453-4fa4-b6d0-4187c6d7a41b.png) ![WX20231029-160406@2x](https://user-images.githubusercontent.com/59017650/278858678-6c50ce74-1de4-4149-b562-bc49b885ca35.png) ![WX20231029-160858@2x](https://user-images.githubusercontent.com/59017650/278858736-827663f2-ebc8-4774-b812-b1ab375479ae.png)
> 
> Anyway, thanks for your detailed check and we'll take your feedback into consideration as we look to enhance our dataset in the future.

_Originally posted by @zwbx in https://github.com/AoiDragon/POPE/issues/8#issuecomment-1793639290_

**Comment by zwbx** [comment]
![Screenshot 2023-11-05 at 16 15 42](https://github.com/AoiDragon/POPE/assets/38418735/a1e194a5-4cf9-407b-bd3b-7fa9cfbf0a4e)

This is image 346707, you can see it only has bbox for category 52, which only refers to "bananas".
There are other similar cases not showing for brief.

**Comment by AoiDragon** [comment]
Hello, @zwbx 

Thanks for your detailed examinations. We get the ground truth objects in the images using the code of computing CHAIR. (You can find them at [here](https://github.com/LisaAnne/Hallucination/blob/master/utils/chair.py)). 

The computation of CHAIR also need to get the ground truth objects in the image. In their code, they get ground truth objects from both the caption and segmentation annotations of COCO.
<img width="866" alt="image" src="https://github.com/AoiDragon/POPE/assets/59017650/a0a0190d-4dd6-40a8-a2b6-1026388ee3e7">

**Comment by Maxlinn** [comment]
> Hello, @zwbx
> 
> Thanks for your detailed examinations. We get the ground truth objects in the images using the code of computing CHAIR. (You can find them at [here](https://github.com/LisaAnne/Hallucination/blob/master/utils/chair.py)).
> 
> The computation of CHAIR also need to get the ground truth objects in the image. In their code, they get ground truth objects from both the caption and segmentation annotations of COCO. <img alt="image" width="866" src="https://user-images.githubusercontent.com/59017650/280716928-a0a0190d-4dd6-40a8-a2b6-1026388ee3e7.png">
> 
> I checked the example you mentioned and found that those objects that not appeared in segmentation annotations are actually appeared in caption annotations. Here are the examples: <img alt="image" width="576" src="https://user-images.githubusercontent.com/59017650/280717300-6b80787a-5795-4b3f-905b-c624ecfeb9e8.png"> The word "container" is mapped to "bowl". <img alt="image" width="774" src="https://user-images.githubusercontent.com/59017650/280717431-15240933-0a2f-4453-9a0d-fbcb331f5834.png"> The word "woman" is mapped to "person".


Hi, may i ask which codebase of CHAIR evaluator did you choose? i found the Hallucination repo is hard to read and still 
 in python2. i'll be much grateful if you could share some hint.

**Comment by zwbx** [comment]
Sorry....I am afraid that I can't offer any suggestions as I have just entered this field after reading your papers.
Returning to this topic, it might worth filtering these kinds of inaccurate captions in original coco labels.

**Comment by AoiDragon** [comment]
As mentioned in #8, we will consider improving this part in the future.
